site_name: HomelabAAS Documentation
nav:
- Home: index.md
- Getting Started: gettingstarted.md
- Walkthrough: walkthrough.md
- Docker Swarm: swarm.md
- Mini DNS: minidns.md
- About: about.md
theme: readthedocs
